"""The operator contract that ships in the wheel (#82): the machine contract
`dirtywork contract` prints, and the Claude Code skill `dirtywork init` renders."""
from __future__ import annotations

import hashlib
import re
import sys
from importlib import resources

from .. import __version__

CONTRACT_NAME = "machine-contract.md"
SKILL_TEMPLATE = "SKILL.md"
SKILL_DIRNAME = "dirtywork"
# The stamp is the first line after the frontmatter; HEX16 covers the whole
# file with this line (and its newline) deleted -- frontmatter included.
STAMP_RE = re.compile(r"^<!-- dirtywork-skill v(?P<version>\S+) sha256:(?P<hash>[0-9a-f]{16})\b")
_FRONTMATTER_END = "\n---\n"


def read(name: str) -> str:
    """The packaged file `name`, decoded as UTF-8."""
    return resources.files(__package__).joinpath(name).read_text(encoding="utf-8")


def _digest(body: str) -> str:
    return hashlib.sha256(body.encode("utf-8")).hexdigest()[:16]


def _split_frontmatter(text: str) -> tuple[str, str]:
    """(frontmatter including both `---` lines and the newline after the
    closing one, everything after it). ValueError if there is no frontmatter."""
    if not text.startswith("---\n"):
        raise ValueError("no frontmatter")
    end = text.index(_FRONTMATTER_END, 4) + len(_FRONTMATTER_END)
    return text[:end], text[end:]


def render_skill(version: str) -> str:
    """The skill text `init` writes for `version`: the template with {{VERSION}}
    replaced (str.replace, never str.format -- the braces are literal in the
    template) and the stamp inserted as the first line after the frontmatter."""
    text = read(SKILL_TEMPLATE).replace("{{VERSION}}", version)
    head, body = _split_frontmatter(text)
    stamp = (f"<!-- dirtywork-skill v{version} sha256:{_digest(head + body)} — generated by "
             f"`dirtywork init`; your edits are preserved (re-run with --force to overwrite) -->\n")
    return head + stamp + body


def dispatch(args) -> int:
    if args.cmd == "contract":
        sys.stdout.write(read(CONTRACT_NAME))
        return 0
    raise NotImplementedError("init")  # W2a
